# Tombol tambahan mpv (bawaan tetap berlaku: Space jeda, panah seek, m mute, f fullscreen, q keluar)
WHEEL_UP   add volume 5
WHEEL_DOWN add volume -5
l          cycle-values loop-file inf no
Ctrl+s     screenshot
